CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE TABLE "FactoryPermissions" (
        "PermissionId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        CONSTRAINT "PK_FactoryPermissions" PRIMARY KEY ("PermissionId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE TABLE "FactoryTenants" (
        "TenantId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        CONSTRAINT "PK_FactoryTenants" PRIMARY KEY ("TenantId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE TABLE "FactoryRoles" (
        "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NOT NULL,
        "RoleName" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "FactoryTenantsTenantId" integer NOT NULL,
        CONSTRAINT "PK_FactoryRoles" PRIMARY KEY ("RoleId"),
        CONSTRAINT "FK_FactoryRoles_FactoryTenants_FactoryTenantsTenantId" FOREIGN KEY ("FactoryTenantsTenantId") REFERENCES "FactoryTenants" ("TenantId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE TABLE "FactoryUsers" (
        "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NOT NULL,
        "Username" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "MFAEnabled" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        "FactoryTenantsTenantId" integer NOT NULL,
        CONSTRAINT "PK_FactoryUsers" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_FactoryUsers_FactoryTenants_FactoryTenantsTenantId" FOREIGN KEY ("FactoryTenantsTenantId") REFERENCES "FactoryTenants" ("TenantId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE TABLE "FactoryRolePermissions" (
        "RoleId" integer NOT NULL,
        "PermissionId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        CONSTRAINT "PK_FactoryRolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "FK_FactoryRolePermissions_FactoryPermissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "FactoryPermissions" ("PermissionId") ON DELETE CASCADE,
        CONSTRAINT "FK_FactoryRolePermissions_FactoryRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "FactoryRoles" ("RoleId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE TABLE "FactoryUserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" integer,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" integer,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" integer,
        CONSTRAINT "PK_FactoryUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_FactoryUserRoles_FactoryRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "FactoryRoles" ("RoleId") ON DELETE CASCADE,
        CONSTRAINT "FK_FactoryUserRoles_FactoryUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "FactoryUsers" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE INDEX "IX_FactoryRolePermissions_PermissionId" ON "FactoryRolePermissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE INDEX "IX_FactoryRoles_FactoryTenantsTenantId" ON "FactoryRoles" ("FactoryTenantsTenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE INDEX "IX_FactoryUserRoles_RoleId" ON "FactoryUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    CREATE INDEX "IX_FactoryUsers_FactoryTenantsTenantId" ON "FactoryUsers" ("FactoryTenantsTenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707064618_InitSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250707064618_InitSchema', '8.0.0');
    END IF;
END $EF$;
COMMIT;

